name: coverage
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - run: ./gomod.sh
    - run: ./gotest.sh
    - uses: codecov/codecov-action@v1.0.2
      with:
        token: abe646af-1c26-455f-92cf-e08552c34d0b
        file: ./cover.out
